##### Imports

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
dataset = pd.read_csv("./datasets/mat.csv")
dataset.columns=[i for i in range(dataset.shape[1])]
dataset

0   1   2   3   4
0   4   5   3   6   1
1   8  10   6  12   2
2   3   3   3   3   3
3   7   1   9   0   8
4  14   2  18   0  16

In [37]:
dataset.shape[0]

5

In [47]:
# generate a random matrix
lines = dataset.shape[0]
columns = dataset.shape[1]

matrix_2 = [[]] * lines
for i in range(len(dataset) - 1):
    for j in range(i + 1, len(dataset)):
        diff = np.diff((dataset[i], dataset[j]), axis=0) * (-1)
        matrix_2 = np.concatenate((matrix_2, diff.T), axis=1)

print(dataset)
print("-----------------------------------")
print(matrix_2)
print("-----------------------------------")

    0   1   2   3   4
0   4   5   3   6   1
1   8  10   6  12   2
2   3   3   3   3   3
3   7   1   9   0   8
4  14   2  18   0  16
-----------------------------------
[[ -1.   1.  -2.   3.   2.  -1.   4.  -3.   2.   5.]
 [ -2.   2.  -4.   6.   4.  -2.   8.  -6.   4.  10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  6.  -2.   7.  -1.  -8.   1.  -7.   9.   1.  -8.]
 [ 12.  -4.  14.  -2. -16.   2. -14.  18.   2. -16.]]
-----------------------------------


In [48]:
matrix_3 = matrix_2 / (np.max(matrix_2) - np.min(matrix_2))
print(matrix_3)

[[-0.02941176  0.02941176 -0.05882353  0.08823529  0.05882353 -0.02941176
   0.11764706 -0.08823529  0.05882353  0.14705882]
 [-0.05882353  0.05882353 -0.11764706  0.17647059  0.11764706 -0.05882353
   0.23529412 -0.17647059  0.11764706  0.29411765]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.17647059 -0.05882353  0.20588235 -0.02941176 -0.23529412  0.02941176
  -0.20588235  0.26470588  0.02941176 -0.23529412]
 [ 0.35294118 -0.11764706  0.41176471 -0.05882353 -0.47058824  0.05882353
  -0.41176471  0.52941176  0.05882353 -0.47058824]]


In [49]:
histogram = [0] * 21


In [50]:
j=1
for i in range(21):
    histogram[i] = j
    j = round(j + 0.1, 1)

for i in range(len(histogram)):
    val = histogram[i]
    histogram[i] = 0
    for j in range(len(matrix_3)):
        for k in range(len(matrix_3[0])):
            if matrix_3[j][k] >= val and matrix_3[j][k] < round(val + 0.1, 1):
                histogram[i] += 1    
                
histogram = np.array(histogram)
print(histogram / sum(histogram))                

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]


C:\Users\TP\AppData\Local\Temp\ipykernel_10020\1525299249.py:15: RuntimeWarning: invalid value encountered in divide
  print(histogram / sum(histogram))
